apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-customer
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ms-customer
    spec:
      containers:
        - name: ms-customer
          image: acrbootcamp2022.azurecr.io/ms-customer:v1
          ports:
            - name: http
              containerPort: 8080
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ms-customer-svc
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: ms-customer