server:
    port: 8080
spring:
    data:
        mongodb:
            # Azure portal
        #uri: "mongodb+srv://afmancilla:Bootcamp2022@cluster0.nh4vc.mongodb.net/bootcampodb"
            uri: "mongodb://bootcamp2022:bkL7FhCZaRF3gosyJcF1Dwj0LD7vfx8rYEj9RopubTErTP28yD48KmHIx20ijEzryTWPjT06dZ2Jh92LcsRMvQ==@bootcamp2022.mongo.cosmos.azure.com:10255/?ssl=true&replicaSet=globaldb&retrywrites=false&maxIdleTimeMS=120000&appName=@bootcamp2022@"
            database: bootcamp2022db
#https://cloud.mongodb.com/
#uri: "mongodb+srv://afmancilla:Bootcamp2022@cluster0.nh4vc.mongodb.net/bootcampodb"

application:
    endpoints:
        url:
            #valid_address: http://run.mocky.io/v3/d1d95b0c-349d-461b-8c6f-56b9c499c43e
            valid_address: https://jsonplaceholder.typicode.com/users